spring.application.name=dc_fin_soft
spring.datasource.url=jdbc:postgresql://localhost:3766/devclub_dev_db1
spring.datasource.username=devwmu_dev
spring.datasource.password=RNILP3jJ6v-gZO1KQsm5tmzUWNr0y4dao1N0B6VhFRQ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/finance_doc.html

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wmudeveloperclubemails@gmail.com
spring.mail.password=heubhgotndsgbnyx

spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true